### ISSUE TITLE
The return object of `insert` is misleading

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/pymilvus-orm#198]
![bug](https://user-images.githubusercontent.com/51370125/123574708-f52f8b00-d802-11eb-9083-2b2f7c5647dd.png)

As the picture presented, insert returns a `pymilvus_orm.search.xxx`, it's very much misleading

**Comment by xiaofan-luan** [comment]
Good catch, any suggestion on how we can move this to a separate without on user perception？

**Comment by xiaofan-luan** [comment]
@xiaocai2333 we need to fix that. feel uncomfortable about this

**Comment by xiaocai2333** [comment]
This problem should be solved by pr #231 . Now the renderings are as follows:

![image](https://user-images.githubusercontent.com/46207236/124529975-34329180-de3e-11eb-8677-2661074e885c.png)

**Comment by xiaocai2333** [comment]
Do you think `MutationResult` should not be placed in the `search` file?

**Comment by XuanYang-cn** [comment]
Closing for fixed
