### ISSUE TITLE
Possibility to remove entity by ids.

### ISSUE THREAD

**Issue by smthngslv** [milvus-io/pymilvus-orm#232]
As the official documentation says, in version v.1.1.1 it is possible to delete entities by ids with Milvus.delete_entity_by_id method. Can I delete entities in 2.0.0 version somehow?

**Comment by xiaofan-luan** [comment]
We are on our way to implement delete. It is a little bit complicated, but the design doc should be ready in the next two weeks. Hopefully we can have delete on Milvus 2.0 stable version, please join our discussion if you are interested

**Comment by XuanYang-cn** [comment]
dup to https://github.com/milvus-io/milvus/issues/7130, closing
