### ISSUE TITLE
pymilvus-orm API tutorial sample code should be updated

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/pymilvus-orm#238]
check the info here:
https://github.com/milvus-io/web-content/issues/614#issue-932317026

**Comment by XuanYang-cn** [comment]
/assign
/unassign @czs007 

We are working on it.

**Comment by XuanYang-cn** [comment]
It's been fixed
/unassign
/assign @yanliang567

**Comment by XuanYang-cn** [comment]
cherry-picking #241

**Comment by XuanYang-cn** [comment]
> cherry-picking #241

cherry-picked

**Comment by XuanYang-cn** [comment]
@yanliang567 It's updated on the [official docs](https://milvus.io/api-reference/pymilvus-orm/v2.0.0rc1/tutorial.html), Please have a check

**Comment by XuanYang-cn** [comment]
solved
