### ISSUE TITLE
Unable to run the hello_milvus tutorial code after Milvus cluster installation

### ISSUE THREAD

**Issue by jpweng** [milvus-io/pymilvus-orm#258]
I installed the Milvus cluster on my local machine (ubuntu 20.04) by simply following this step: [https://milvus.io/docs/v2.0.0/install_cluster-docker.md](https://milvus.io/docs/v2.0.0/install_cluster-docker.md)

Then I installed pymilvus-orm using `pip install pymilvus-orm==2.0.0rc1`

I tried to run it (using Python3), but it fails at `# create connection
    connections.connect()` with error:

`Traceback (most recent call last):
  File "hello_milvus.py", line 74, in <module>
    hello_milvus()
  File "hello_milvus.py", line 19, in hello_milvus
    connections.connect(alias="default", host="localhost", port="19530")
  File "/home/jp/.local/lib/python3.8/site-packages/pymilvus_orm/connections.py", line 158, in connect
    conn = connect_milvus(**kwargs)
  File "/home/jp/.local/lib/python3.8/site-packages/pymilvus_orm/connections.py", line 148, in connect_milvus
    return Milvus(tmp_host, tmp_port, handler, pool, **tmp_kwargs)
  File "/home/jp/.local/lib/python3.8/site-packages/pymilvus/client/stub.py", line 122, in __init__
    self._update_connection_pool()
  File "/home/jp/.local/lib/python3.8/site-packages/pymilvus/client/stub.py", line 175, in _update_connection_pool
    self._wait_for_healthy()
  File "/home/jp/.local/lib/python3.8/site-packages/pymilvus/client/stub.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/home/jp/.local/lib/python3.8/site-packages/pymilvus/client/stub.py", line 148, in _wait_for_healthy
    raise Exception("server is not healthy, please try again later")
Exception: server is not healthy, please try again later
`

The same steps with standalone milvus works fine though.

**Comment by xiaofan-luan** [comment]
@jpweng seems that server is not ready, did you check your docker states?

**Comment by jpweng** [comment]
@xiaofan-luan  Here is the output of `docker ps -a`:

CONTAINER ID   IMAGE                                         COMMAND                   CREATED        STATUS                        PORTS                      NAMES
0854a9b42998   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1   "/tini -- milvus run…"    23 hours ago   Up About a minute                                        milvus-querynode
53ad8c46b7ff   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1   "/tini -- milvus run…"    23 hours ago   Up About a minute                                        milvus-datanode
c2a3e813acc1   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1   "/tini -- milvus run…"    23 hours ago   Up About a minute                                        milvus-indexnode
8819641d7dc1   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1   "/tini -- milvus run…"    23 hours ago   Up About a minute                                        milvus-datacoord
cb2cccb386c8   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1   "/tini -- milvus run…"    23 hours ago   Up About a minute                                        milvus-querycoord
a134da8854ab   milvusdb/milvus:v2.0.0-rc2-20210712-a8e5fd2   "/tini -- milvus run…"    23 hours ago   Up About a minute                                        milvus-rootcoord
978416e5d487   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1   "/tini -- milvus run…"    23 hours ago   Up About a minute                                        milvus-indexcoord
fed0ead35ac4   apachepulsar/pulsar:latest                    "/bin/sh -c '\n      …"   23 hours ago   Up About a minute                                        milvus-pulsar
6abd431bf743   quay.io/coreos/etcd:latest                    "etcd -listen-peer-u…"    23 hours ago   Up About a minute (healthy)   2379-2380/tcp              milvus-etcd
998dc44c5619   milvusdb/milvus:v2.0.0-rc1-20210628-b87baa1   "/tini -- milvus run…"    23 hours ago   Up About a minute             0.0.0.0:19530->19530/tcp   milvus-proxy
902af82e22ec   minio/minio:RELEASE.2020-12-03T00-03-10Z      "/usr/bin/docker-ent…"    23 hours ago   Up About a minute (healthy)   9000/tcp                   milvus-minio

**Comment by jpweng** [comment]
Now this just changed after running docker ps -a: `fed0ead35ac4   apachepulsar/pulsar:latest                    "/bin/sh -c '\n      …"   23 hours ago   Exited (1) 5 minutes ago                              milvus-pulsar
`

**Comment by junsikh** [comment]
Hi, I'm having the same issue with milvus-standalone when docker is running perfectly fine with more-than-enough resources. I've yet to figure out what the problem is. Sometimes I can access to milvus after waiting for more than 10 minutes and it takes forever to add 30 (not 3000) vectors into the database. Never had this issue with previous versions.

**Comment by xiaofan-luan** [comment]
> It seems that deleting `volumes` folder helps solve the connection issue.

Thanks for the answer !

**Comment by XuanYang-cn** [comment]
Stale issue, closing
