### ISSUE TITLE
Method calc_distance is  not available in pymilvus utility

### ISSUE THREAD

**Issue by GopinathCool** [milvus-io/pymilvus-orm#260]
When running the [example.py](https://github.com/milvus-io/pymilvus-orm/blob/main/examples/example.py), I got the below error.

Traceback (most recent call last):
  File "milvus_example.py", line 111, in <module>
    results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r, params=params)
AttributeError: module 'pymilvus_orm.utility' has no attribute 'calc_distance'

**Comment by NotRyan** [comment]
Hi GopinathCool,

'calc_distance' has been recently implemented, but it has not been included in an official release yet, hence the error. For a version of example.py that will work with a current release version, you can use an [older version of example.py](https://github.com/milvus-io/pymilvus-orm/blob/2.0.0rc1/examples/example.py) 

Alternatively, if you'd like to try out the 'calc_distance' function, you can install a more recent unreleased development version of pymilvus-orm with

$`pip install --extra-index-url https://test.pypi.org/simple/ pymilvus-orm==2.0.0rc3.dev6`

We generally do not recommend using development versions of pymilvus-orm in production environments. Note that this will also require a Milvus version of 2.0.0-rc2 or above.

**Comment by XuanYang-cn** [comment]
Stale issue, closing
