### ISSUE TITLE
Milvus 2.0 documentation is missing the flush API

### ISSUE THREAD

**Issue by jingkl** [milvus-io/pymilvus-orm#264]
Milvus 2.0 pymilvus orm documentation is missing the flush API, need relevant interface information

**Comment by NotRyan** [comment]
It is my understanding that flush does not actually exist as part of PyMilvus-ORM right now.

To call for a flush, you have to get the underlying PyMilvus object with utility.get_connection() and then call the flush method on the object. 

````
milvusConnection = pymilvus_orm.utility.get_connection()
milvusConnection.flush([collection_name])

print(type(milvusConnection))

# output:
# <class 'pymilvus.client.stub.Milvus'>
````

Technically, flush is a part of PyMilvus, but not PyMilvus-ORM, so the documentation is correct. In my opinion, I think it would make sense to add a wrapper for flush to pymilvus-orm.
